../rtl/i2c/AHBlite_I2C.v
../rtl/i2c/I2C_Master.v
../rtl/i2c/I2C_top.v
../rtl/i2c/I2C_Slver.v
../rtl/i2c/FIFO.v
../rtl/mcu_cortex_M0/AHBlite_Block_RAM.v
../rtl/mcu_cortex_M0/AHBlite_Decoder.v
../rtl/mcu_cortex_M0/AHBlite_Interconnect.v
../rtl/mcu_cortex_M0/AHBlite_SlaveMUX.v
../rtl/mcu_cortex_M0/AHBlite_UART.v
../rtl/mcu_cortex_M0/AHBlite_WaterLight.v
../rtl/mcu_cortex_M0/Block_RAM.v
../rtl/mcu_cortex_M0/clkuart_pwm.v
../rtl/mcu_cortex_M0/CortexM0_SoC.v
../rtl/mcu_cortex_M0/cortexm0ds_logic.v
../rtl/mcu_cortex_M0/UART_RX.v
../rtl/mcu_cortex_M0/UART_TX.v
../rtl/mcu_cortex_M0/WaterLight.v
./_tb/i2c_test/I2C_Master_test.v
./_tb/i2c_test/I2C_Slver_test.v
./_tb/i2c_test/I2C_top_test.v
./_tb/CortexM0_SoC_vlg_tst.v